name: Lint and format (ruff)

on: [ push, pull_request ]

# From ruff documentation: https://docs.astral.sh/ruff/integrations/#github-actions
jobs:
  ruff:
    runs-on: ubuntu-latest

    # Needed for commiting changes: https://github.com/stefanzweifel/git-auto-commit-action
    permissions:
        contents: write

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4

      - name: Lint and fix issues
        uses: astral-sh/ruff-action@v3
        with:
            args: check --fix
        continue-on-error: true

      - name: Format
        run: ruff format

      - name: Commit Ruff fixes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
            commit_message: 'chore: apply ruff linting and formatting fixes'
